# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180106_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='updated',
            new_name='update',
        ),
    ]
