# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20180110_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
