# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180107_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=100),
        ),
    ]
